config/routes.rb
Depot::Application.routes.draw do

  devise_for :users

  root :to => 'store#index'

  resources :line_items, :carts, :orders

  resources :products do
    resources :comments
    get :who_bought, :on => :member
  end

  namespace :admin do
    resources :users, :products
  end

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
  user ||= User.new       
    case user.role   
      when "admin"
        can :manage, :all
      when "user"
        can :manage, Order, :user_id => user.id
      end
  end
end

app/models/cart.rb
class Cart < ActiveRecord::Base
	has_many :line_items, :dependent => :destroy

	def add_product(product_id)
    current_item = line_items.find_by_product_id(product_id)
    if current_item
      current_item.quantity += 1
    else
      current_item = line_items.build(:product_id => product_id)
      current_item.price = current_item.product.price
    end
    current_item
  end

  def total_price
    line_items.to_a.sum { |item| item.total_price }
  end


	
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :product
  has_ancestry
end

app/models/image.rb
class Image < ActiveRecord::Base
	file_accessor :image
	belongs_to :product
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
	belongs_to :cart
	belongs_to :product
	belongs_to :order

  def total_price
	  product.price * quantity
	end


end

app/models/order.rb
class Order < ActiveRecord::Base
	PAYMENT_TYPES = [ "Check", "Credit card", "Purchase order" ]

  has_many :line_items
  belongs_to :user

  validates :name, :address, :email, :pay_type, :presence => true
  validates :pay_type, :inclusion => PAYMENT_TYPES

  def add_line_items_from_cart(cart)
  	cart.line_items.each do |item|
    	item.cart_id = nil
    	line_items << item
  	end
	end


end

app/models/product.rb
class Product < ActiveRecord::Base
	default_scope :order => 'title'
	before_destroy :ensure_not_referenced_by_any_line_item

	has_many :images, :dependent => :destroy
	has_many :line_items, :dependent => :destroy
	has_many :orders, :through => :line_items
	has_many :comments, :dependent => :destroy

	accepts_nested_attributes_for :images, :allow_destroy => true, 
								:reject_if => proc { |attrs| attrs['image'].blank? }

	validates :title, :description, :presence => true
	validates :title, :uniqueness => true
	validates :title, :length => {:minimum => 10}

	validates :price, :numericality => {:greater_than_or_equal_to => 0.01}
	
	private
		def ensure_not_referenced_by_any_line_item
			errors.add(:base, 'Line Items present') unless line_items.count.zero?
		end

end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :orders
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  private

	def current_cart
		Cart.find(session[:cart_id])
	rescue ActiveRecord::RecordNotFound
		cart = Cart.create
		session[:cart_id] = cart.id
		cart
	end

	rescue_from CanCan::AccessDenied do |exception|
		redirect_to root_url, :alert => exception.message
	end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
	def show
		begin
			@cart = Cart.find(params[:id])
		rescue
			logger.error "Attempt to access invalid cart #{params[:id]}"
      redirect_to store_url, :notice => 'Invalid cart'
		end
	end

  def destroy
    current_cart.destroy
    session[:cart_id] = nil

    respond_to do |format|
      format.html { redirect_to store_url }
      format.js
    end
  end


end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :load_product
  def index
    @comments = @product.comments  
    @comment = @product.comments.build(:parent_id => params[:parent_id])
  end

  def load_product
    @product = Product.find(params[:product_id])
  end

  def new
    @comment = @product.comments.build(:parent_id => params[:parent_id])
  end

  def create
    @comment = @product.comments.build(params[:comment])
    if @comment.save
      redirect_to product_comments_path(@product), :notice => 'Comments added.'
    else
      render :new
    end
  end

end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController

	def create
  	@cart = current_cart
    product = Product.find(params[:product_id])
    @line_item = @cart.add_product(product.id)
    session[:counter] = 0

    respond_to do |format|
      if @line_item.save
        format.html { redirect_to(store_url) }
        format.js { @current_item = @line_item }
      else
        format.html { render :new }
      end
    end

	end

  def destroy
    @line_item = LineItem.find(params[:id])
    @line_item.destroy
    
    respond_to do |format|
      format.html { redirect_to current_cart }
      format.js
    end
  end


end

app/controllers/orders_controller.rb
class OrdersController < InheritedResources::Base
  load_and_authorize_resource
  
  def index
    #@orders = Order.order('created_at desc').page params[:page]
  end

  def show
    #@order = Order.find(params[:id])
  end

  def edit
    #@order = Order.find(params[:id])
  end

  def new
    @cart = current_cart
    if @cart.line_items.empty?
      redirect_to root_url, :notice => "Your cart is empty"
      return
    end
    #@order = Order.new
  end

  def create
    @order = Order.new(params[:order])
    @order.user = current_user
    @order.add_line_items_from_cart(current_cart)

    if @order.save
      Cart.destroy(session[:cart_id])
      session[:cart_id] = nil
      Notifier.order_received(@order).deliver
      redirect_to root_url, :notice => 'Thank you for your order.'
    else
      render :new
    end
  end

end

app/controllers/products_controller.rb
class ProductsController < InheritedResources::Base

	def who_bought
    @product = Product.find(params[:id])
    respond_to do |format|
    format.atom
    format.xml { render :xml => @product }
    end
  end


end

app/controllers/store_controller.rb
class StoreController < ApplicationController
	before_filter :counter
  def index
  	@products = Product.all
  	@cart = current_cart
  end

  def counter
  	session[:counter] = session[:counter].is_a?(Fixnum) ? session[:counter] + 1 : 0
  end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  
	def hidden_div_if(condition, attributes = {}, &block)
    if condition
      attributes["style"] = "display: none"
    end
    content_tag("div", attributes, &block)
  end

end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
	def nested_comments(comments)
  comments.map do |comment, sub_comments|
    render(comment) + content_tag(:div, nested_comments(sub_comments), :class => "nested_comments")
  end.join.html_safe
end


end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/views/carts/_cart.html.haml
-unless cart.line_items.empty?
  %table
    =render cart.line_items
    %tr.total_line
      %td Total
      %td.total_cell=number_to_currency @cart.total_price
  =button_to 'Empty cart', @cart, :method => :delete, :confirm => 'Are you sure?', :remote => true
  =button_to "Checkout", new_order_path, :method => :get

app/views/carts/destroy.js.erb
$('#cart').hide();

app/views/carts/show.html.haml
=render @cart

app/views/comments/_comment.html.haml
.comment
	%p=comment.title
	%p=comment.content
	%p=link_to "Reply", new_product_comment_path(:parent_id => comment)

app/views/comments/_form.html.haml
=semantic_form_for [@product, @comment] do |f|
  =f.inputs "Comments" do
    =f.input :title
    =f.input :content, :as => :text
    =f.input :parent_id, :as => :hidden
  =f.buttons
  

app/views/comments/index.html.haml
#comments
  = nested_comments @comments.arrange(:order => :created_at)
  =render "form"

app/views/comments/new.html.haml
=render @comment.parent
=render "form"

app/views/line_items/_line_item.html.haml
- if line_item == @current_item
  %tr#current_item.current_item
- else
  %tr.current_item
%td
  = line_item.quantity
  \×
%td= line_item.product.title
%td.item_price= number_to_currency(line_item.total_price)
%td=button_to 'Delete', line_item_path(line_item), :method => :delete, :confirm => 'Are you sure?', :remote => true

app/views/line_items/create.js.erb
$('#cart').show();
$('#cart').html("<%= escape_javascript(render @cart) %>");
$('#current_item').css({'background-color':'#88ff88'}).animate({'background-color':'#114411'}, 1000);

app/views/line_items/destroy.js.erb
$('.current_item').hide();

app/views/orders/_form.html.haml
=semantic_form_for @order do |f|
  =f.inputs "Order" do
    =f.input :name
    =f.input :address, :as => :text, :rows => 3, :cols => 40
    =f.input :email, :size => 40
    =f.input :pay_type, :collection => Order::PAYMENT_TYPES, :prompt => 'Select a payment method'
  =f.buttons

app/views/orders/edit.html.haml
=render "form"

app/views/orders/index.html.haml
%h1 Listing orders
%table
  %tr
    %th Name
    %th Address
    %th Email
    %th Pay type
    %th
    %th
    %th
    - @orders.each do |order|
      %tr
      %td= order.name
      %td= order.user_id
      %td= order.address
      %td= order.email
      %td= order.pay_type
      %td= link_to 'Show', order
      %td= link_to 'Edit', edit_order_path(order)
      %td= link_to 'Destroy', order, :confirm => 'Are you sure?', :method => :delete
= link_to 'New Order', new_order_path

app/views/orders/new.html.haml
.depot_form
  %fieldset
    %legend Please Enter Your Details
    = render 'form'

app/views/orders/show.html.haml
=@order.name