config/routes.rb
Depot::Application.routes.draw do

  devise_for :users

  root :to => 'store#index'

  resources :line_items, :carts, :orders

  resources :products do
    resources :comments
    get :who_bought, :on => :member
  end

  namespace :admin do
    resources :users, :products
  end

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
  user ||= User.new       
    case user.role   
      when "admin"
        can :manage, :all
      when "user"
        can :manage, Order, :user_id => user.id
      end
  end
end

app/models/cart.rb
class Cart < ActiveRecord::Base
	has_many :line_items, :dependent => :destroy

	def add_product(product_id)
    current_item = line_items.find_by_product_id(product_id)
    if current_item
      current_item.quantity += 1
    else
      current_item = line_items.build(:product_id => product_id)
      current_item.price = current_item.product.price
    end
    current_item
  end

  def total_price
    line_items.to_a.sum { |item| item.total_price }
  end


	
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :product
  has_ancestry
end

app/models/image.rb
class Image < ActiveRecord::Base
	file_accessor :image
	belongs_to :product
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
	belongs_to :cart
	belongs_to :product
	belongs_to :order

  def total_price
	  product.price * quantity
	end


end

app/models/order.rb
class Order < ActiveRecord::Base
	PAYMENT_TYPES = [ "Check", "Credit card", "Purchase order" ]

  has_many :line_items
  belongs_to :user

  validates :name, :address, :email, :pay_type, :presence => true
  validates :pay_type, :inclusion => PAYMENT_TYPES

  def add_line_items_from_cart(cart)
  	cart.line_items.each do |item|
    	item.cart_id = nil
    	line_items << item
  	end
	end


end

app/models/product.rb
class Product < ActiveRecord::Base
	default_scope :order => 'title'
	before_destroy :ensure_not_referenced_by_any_line_item

	has_many :images, :dependent => :destroy
	has_many :line_items, :dependent => :destroy
	has_many :orders, :through => :line_items
	has_many :comments, :dependent => :destroy

	accepts_nested_attributes_for :images, :allow_destroy => true, 
								:reject_if => proc { |attrs| attrs['image'].blank? }

	validates :title, :description, :presence => true
	validates :title, :uniqueness => true
	validates :title, :length => {:minimum => 10}

	validates :price, :numericality => {:greater_than_or_equal_to => 0.01}
	
	private
		def ensure_not_referenced_by_any_line_item
			errors.add(:base, 'Line Items present') unless line_items.count.zero?
		end

end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :orders
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < InheritedResources::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  private

	def current_cart
		Cart.find(session[:cart_id])
	rescue ActiveRecord::RecordNotFound
		cart = Cart.create
		session[:cart_id] = cart.id
		cart
	end

	rescue_from CanCan::AccessDenied do |exception|
		redirect_to root_url, :alert => exception.message
	end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
	def show
		begin
			@cart = Cart.find(params[:id])
		rescue
			logger.error "Attempt to access invalid cart #{params[:id]}"
      redirect_to store_url, :notice => 'Invalid cart'
		end
	end

  def destroy
    current_cart.destroy
    session[:cart_id] = nil

    respond_to do |format|
      format.html { redirect_to store_url }
      format.js
    end
  end


end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :load_product
  def index
    @comments = @product.comments  
    @comment = @product.comments.build(:parent_id => params[:parent_id])
  end

  def load_product
    @product = Product.find(params[:product_id])
  end

  def new
    @comment = @product.comments.build(:parent_id => params[:parent_id])
  end

  def create
    @comment = @product.comments.build(params[:comment])
    if @comment.save
      redirect_to product_comments_path(@product), :notice => 'Comments added.'
    else
      render :new
    end
  end

end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController

	def create
  	@cart = current_cart
    product = Product.find(params[:product_id])
    @line_item = @cart.add_product(product.id)
    session[:counter] = 0

    respond_to do |format|
      if @line_item.save
        format.html { redirect_to(store_url) }
        format.js { @current_item = @line_item }
      else
        format.html { render :new }
      end
    end

	end

  def destroy
    @line_item = LineItem.find(params[:id])
    @line_item.destroy
    
    respond_to do |format|
      format.html { redirect_to current_cart }
      format.js
    end
  end


end

app/controllers/orders_controller.rb
class OrdersController < InheritedResources::Base
  load_and_authorize_resource
  
  def index
    #@orders = Order.order('created_at desc').page params[:page]
  end

  def show
    #@order = Order.find(params[:id])
  end

  def edit
    #@order = Order.find(params[:id])
  end

  def new
    @cart = current_cart
    if @cart.line_items.empty?
      redirect_to root_url, :notice => "Your cart is empty"
      return
    end
    #@order = Order.new
  end

  def create
    @order = Order.new(params[:order])
    @order.user = current_user
    @order.add_line_items_from_cart(current_cart)

    if @order.save
      Cart.destroy(session[:cart_id])
      session[:cart_id] = nil
      Notifier.order_received(@order).deliver
      redirect_to root_url, :notice => 'Thank you for your order.'
    else
      render :new
    end
  end

end

app/controllers/products_controller.rb
class ProductsController < InheritedResources::Base

	def who_bought
    @product = Product.find(params[:id])
    respond_to do |format|
    format.atom
    format.xml { render :xml => @product }
    end
  end


end

app/controllers/store_controller.rb
class StoreController < ApplicationController
	before_filter :counter
  def index
  	@products = Product.all
  	@cart = current_cart
  end

  def counter
  	session[:counter] = session[:counter].is_a?(Fixnum) ? session[:counter] + 1 : 0
  end

end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  
	def hidden_div_if(condition, attributes = {}, &block)
    if condition
      attributes["style"] = "display: none"
    end
    content_tag("div", attributes, &block)
  end

end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
	def nested_comments(comments)
  comments.map do |comment, sub_comments|
    render(comment) + content_tag(:div, nested_comments(sub_comments), :class => "nested_comments")
  end.join.html_safe
end


end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/views/admin/products/_form.html.erb
  <div class="group">
    <%= f.label :title, t("activerecord.attributes.product.title", :default => "Title"), :class => :label %>
    <%= f.text_field :title, :class => 'text_field' %>
    <span class="description">Ex: a simple text</span>
  </div>

  <div class="group">
    <%= f.label :description, t("activerecord.attributes.product.description", :default => "Description"), :class => :label %>
    <%= f.text_area :description, :class => 'text_area' %>
    <span class="description">Ex: a simple text</span>
  </div>

  <div class="group">
    <%= f.label :image_url, t("activerecord.attributes.product.image_url", :default => "Image url"), :class => :label %>
    <%= f.text_field :image_url, :class => 'text_field' %>
    <span class="description">Ex: a simple text</span>
  </div>

  <div class="group">
    <%= f.label :price, t("activerecord.attributes.product.price", :default => "Price"), :class => :label %>
    <%= f.text_field :price, :class => 'text_field' %>
    <span class="description">Ex: a simple text</span>
  </div>

  <div class="group">
    <%= f.label :cover_image_uid, t("activerecord.attributes.product.cover_image_uid", :default => "Cover image uid"), :class => :label %>
    <%= f.text_field :cover_image_uid, :class => 'text_field' %>
    <span class="description">Ex: a simple text</span>
  </div>

  <div class="group">
    <%= f.label :cover_image_name, t("activerecord.attributes.product.cover_image_name", :default => "Cover image name"), :class => :label %>
    <%= f.text_field :cover_image_name, :class => 'text_field' %>
    <span class="description">Ex: a simple text</span>
  </div>
        
<div class="group navform wat-cf">
  <button class="button" type="submit">
    <%= image_tag("web-app-theme/icons/tick.png", :alt => "#{t("web-app-theme.save", :default => "Save")}") %> <%= t("web-app-theme.save", :default => "Save") %>
  </button>
  <span class="text_button_padding"><%= t("web-app-theme.or", :default => "or") %></span>
	<%= link_to t("web-app-theme.cancel", :default => "Cancel"), admin_products_path, :class => "text_button_padding link_button" %>
</div>

app/views/admin/products/_sidebar.html.erb
<div class="block notice">
  <h3>Simple Block</h3>
  <div class="content">
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
  </div>
</div>
<div class="block">
  <h3>Links</h3>
  <ul class="navigation">
    <li><a href="#">Link 1</a></li>
    <li><a href="#">Link 2</a></li>
  </ul>
</div>

app/views/admin/products/edit.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List")}", admin_products_path  %></li>
      <li><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_admin_product_path %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_admin_product_path %></li>
    </ul>
  </div>          
  <div class="content">            
    <h2 class="title"><%= t("web-app-theme.edit", :default => "Edit") %> Product</h2>
    <div class="inner">
      <%= form_for @product, :url => admin_product_path(@product), :html => { :class => :form } do |f| -%>
        <%= render :partial => "form", :locals => {:f => f} %>
      <% end -%>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/admin/products/index.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first active"><%= link_to "#{t("web-app-theme.list", :default => "List")}", admin_products_path  %></li>
      <li><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_admin_product_path %></li>
    </ul>
  </div>          
  <div class="content">          
    <h2 class="title"><%= t("web-app-theme.all", :default => "All")  %> Products</h2>
    <div class="inner">
      <table class="table">
        <tr>             
          <th class="first">ID</th>
                    <th>
            <%= t("activerecord.attributes.admin_product.title", :default => t("activerecord.labels.title", :default => "Title")) %>
          </th>
                    <th><%= t("web-app-theme.created_at", :default => "Created at")  %></th>
          <th class="last">&nbsp;</th>
        </tr>
        <% @products.each do |product| -%>
        <tr class="<%= cycle("odd", "even") %>">
          <td>
            <%= product.id %>
          </td>
                    <td>
            <%= link_to product.title, admin_product_path(product) %>
          </td>
                    <td>
            <%= product.created_at %>
          </td>
          <td class="last">
            <%= link_to "#{t("web-app-theme.show", :default => "Show")}", admin_product_path(product) %> |
            <%= link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_admin_product_path(product) %> |
            <%= link_to "#{t("web-app-theme.delete", :default => "Delete")}", admin_product_path(product), :method => :delete, :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}" %>
          </td>
        </tr>          
        <% end -%>
      </table>
      <div class="actions-bar wat-cf">
        <div class="actions">
        </div>
        
      </div>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/admin/products/new.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List")}", admin_products_path  %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_admin_product_path %></li>
    </ul>
  </div>          
  <div class="content">            
    <h2 class="title"><%= t("web-app-theme.new", :default => "New")%>  Product</h2>
    <div class="inner">
      <%= form_for :product, :url => admin_products_path, :html => { :class => :form } do |f| -%>
        <%= render :partial => "form", :locals => {:f => f} %>
      <% end -%>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/admin/products/show.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List")}", admin_products_path  %></li>
      <li><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_admin_product_path %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.show", :default => "Show")}", admin_product_path %></li>
    </ul>
  </div>          
  <div class="content">
    <div class="inner">
      
        <p>
          <b><%= t("activerecord.attributes.admin_product.title", :default => t("activerecord.labels.title", :default => "Title")) %>:</b>
          <%= @product.title %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.admin_product.description", :default => t("activerecord.labels.description", :default => "Description")) %>:</b>
          <%= @product.description %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.admin_product.image_url", :default => t("activerecord.labels.image_url", :default => "Image url")) %>:</b>
          <%= @product.image_url %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.admin_product.price", :default => t("activerecord.labels.price", :default => "Price")) %>:</b>
          <%= @product.price %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.admin_product.cover_image_uid", :default => t("activerecord.labels.cover_image_uid", :default => "Cover image uid")) %>:</b>
          <%= @product.cover_image_uid %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.admin_product.cover_image_name", :default => t("activerecord.labels.cover_image_name", :default => "Cover image name")) %>:</b>
          <%= @product.cover_image_name %>
        </p>
      <div class="wat-cf">
        <%= link_to image_tag("web-app-theme/icons/application_edit.png", :alt => "#{t("web-app-theme.edit", :default=> "Edit")}") + " " + t("web-app-theme.edit", :default=> "Edit"), edit_admin_product_path(@product), :class => "button" %> 
        <%= link_to image_tag("web-app-theme/icons/cross.png", :alt => "#{t("web-app-theme.delete", :default=> "Delete")}") + " " + t("web-app-theme.delete", :default => "Delete"), admin_product_path(@product), :method => "delete", :class => "button", :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}" %>
      </div>      
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/products/_form.html.haml
=semantic_nested_form_for @product, :html => {:multipart => true} do |f|
  =f.inputs "Product" do
    =f.input :title
    =f.input :description, :as => :text
    =f.input :price
  =f.fields_for :images do |image_f|
    =image_f.input :name
    =image_f.input :image, :as => :file
    =image_f.input :retained_image, :as => :hidden
    =image_f.link_to_remove "Remove this task"
  %p=f.link_to_add "Add image", :images
  =f.buttons

app/views/products/_product.html.haml
.entry
  -if !product.images.any?
    =link_to image_submit_tag(product.images.first.image.url), line_items_path(:product_id => product), :method => :post, :remote => true
  %h3= product.title
  = sanitize product.description
  .price_line
    %span.price= number_to_currency product.price
    =button_to 'Add to Cart', line_items_path(:product_id => product), :remote => true

app/views/products/index.html.haml
#product_list
  %h1 Listing products
  %table
    - @products.each do |product|
      %tr{:class => cycle('list_line_odd', 'list_line_even')}
        %td
          -if !product.images.empty?
            =image_tag(product.images.first.image.url, :class => "list_image") 
        %td.list_description
          %dl
            %dt= product.title
            %dd= truncate(strip_tags(product.description), |
                :length => 80)                            |
        %td.list_actions
          = link_to 'Show', product
          %br/
          = link_to 'Edit', edit_product_path(product)
          %br/
          = link_to 'Destroy', product,  |
            :confirm => 'Are you sure?', |
            :method => :delete           |
%br/
= link_to 'New product', new_product_path

app/views/products/new.html.haml
=render "form"

app/views/products/show.html.haml
%p=@product.title
%p=@product.description
%p=@product.price
-@product.images.each do |i|
	%p=link_to(image_tag(i.image.thumb('80x80').url), i.image.url)

%p=link_to "Comments", product_comments_path(@product)